linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-use-default: true
