package main

import (
	"fmt"
	"sort"
	"strings"
)

// cmdCompletion prints a shell completion script generated from the
// command table, so completions always match the real CLI.
func cmdCompletion(a *App, inv *invocation) error {
	if len(inv.args) != 1 {
		return usageErr("completion needs one of: bash, zsh, fish")
	}
	cmds := commands()
	switch inv.args[0] {
	case "bash":
		a.UI.Print(bashCompletion(cmds))
	case "zsh":
		a.UI.Print(zshCompletion(cmds))
	case "fish":
		a.UI.Print(fishCompletion(cmds))
	default:
		return usageErr("completion needs one of: bash, zsh, fish")
	}
	return nil
}

func cmdNames(cmds []*command) []string {
	var n []string
	for _, c := range cmds {
		n = append(n, c.name)
	}
	return n
}

func flagWords(c *command) []string {
	var out []string
	for _, f := range append(append([]string{}, c.flags...), "yes", "help", "no-color") {
		out = append(out, "--"+f)
	}
	sort.Strings(out)
	return out
}

// takesPackages reports whether a command completes package names.
func takesPackages(name string) bool {
	switch name {
	case "install", "remove", "update", "info":
		return true
	}
	return false
}

func bashCompletion(cmds []*command) string {
	var cases strings.Builder
	for _, c := range cmds {
		pk := ""
		if takesPackages(c.name) {
			pk = ` $(debforge list --names 2>/dev/null)`
		}
		fmt.Fprintf(&cases, "    %s) COMPREPLY=($(compgen -W \"%s%s\" -- \"$cur\")) ;;\n", c.name, strings.Join(flagWords(c), " "), pk)
	}
	return `# bash completion for debforge (generated by 'debforge completion bash')
_debforge() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=($(compgen -W "` + strings.Join(cmdNames(cmds), " ") + ` --help --version" -- "$cur"))
    return
  fi
  case "${COMP_WORDS[1]}" in
` + cases.String() + `  esac
}
complete -F _debforge debforge`
}

func zshCompletion(cmds []*command) string {
	var b strings.Builder
	b.WriteString("#compdef debforge\n# zsh completion for debforge (generated by 'debforge completion zsh')\n_debforge() {\n  local -a cmds\n  cmds=(\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "    '%s:%s'\n", c.name, strings.ReplaceAll(c.help, "'", ""))
	}
	b.WriteString("  )\n  if (( CURRENT == 2 )); then\n    _describe command cmds\n    return\n  fi\n  case $words[2] in\n")
	for _, c := range cmds {
		pk := ""
		if takesPackages(c.name) {
			pk = ` ${(f)"$(debforge list --names 2>/dev/null)"}`
		}
		fmt.Fprintf(&b, "    %s) compadd -- %s%s ;;\n", c.name, strings.Join(flagWords(c), " "), pk)
	}
	b.WriteString("  esac\n}\n_debforge \"$@\"")
	return b.String()
}

func fishCompletion(cmds []*command) string {
	var b strings.Builder
	b.WriteString("# fish completion for debforge (generated by 'debforge completion fish')\ncomplete -c debforge -f\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "complete -c debforge -n '__fish_use_subcommand' -a %s -d '%s'\n", c.name, strings.ReplaceAll(c.help, "'", ""))
		for _, f := range flagWords(c) {
			fmt.Fprintf(&b, "complete -c debforge -n '__fish_seen_subcommand_from %s' -l %s\n", c.name, strings.TrimPrefix(f, "--"))
		}
		if takesPackages(c.name) {
			fmt.Fprintf(&b, "complete -c debforge -n '__fish_seen_subcommand_from %s' -a '(debforge list --names 2>/dev/null)'\n", c.name)
		}
	}
	return strings.TrimRight(b.String(), "\n")
}
