monitor.alsa.rules = [
  {
    matches = [{ node.name = "~alsa_output.*hdmi*" }]
    actions = {
      update-props = {
        priority.driver  = 100
        priority.session = 100
      }
    }
  }
]