# Wine audio: raise the minimum pulse quantum so Wine's 44100/48000 streams
# don't underrun. Playback latency is less critical than dropouts for games.
pulse.rules = [
    {
        matches = [ { application.process.binary = "wine64-preloader" } ]
        actions = {
            update-props = {
                pulse.min.quantum = 1024/48000
            }
        }
    }
]